name: Publish Html

on:
  push:
    branches: [master, release/*]
  pull_request:
    branches: [master, release/*]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Make Html
        run: docker run --rm -v "${PWD}:/doc" -u "$(id -u):$(id -g)" ohiosupercomputer/docker-sphinx make html

      - name: Publish to the test repo
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} /bin/bash push.sh "osd-documentation-test"
    
      - name: Publish to the main repo
        if: github.event_name == 'push'
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} /bin/bash push.sh "osd-documentation"
